# Generated by Django 4.2.4 on 2023-08-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_details',
        ),
    ]
