# Generated by Django 4.2.4 on 2023-08-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_lis_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lis',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
