# Generated by Django 4.2.4 on 2023-08-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_lis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lis',
            name='uname',
            field=models.CharField(default='', max_length=122),
        ),
    ]
